### PR TITLE
Makes sure cached recent reports are displayed in order.

### LINKED ISSUE #2999: Recent reports on front page are not always ordered
**Describe the bug**
When the recent reports are fetched from the database they're ordered by confirmed date, but when they're found in memcached they're unordered.

**To Reproduce**
Typically it's enough to just view the front page and note the timestamps of the recent reports. If the cache timeout had expired however they'll be correct.

**Expected behavior**
The order should be the same regardless of whether the cache is used or not.

Will supply PR with suggested fix shortly...

### PR DESCRIPTION
**Pull request by joesiltberg**
Fixes #2999

### CODE REVIEW

File: perllib/FixMyStreet/DB/ResultSet/Problem.pm [hunk 1]
```diff
@@ -159,7 +159,7 @@ sub _recent {
             $probs = [ $rs->search({
                 id => [ map { $_->id } @$probs ],
                 %$query,
-            })->all ];
+            }, $attrs)->all ];
```
Comment (joesiltberg) [inline perllib/FixMyStreet/DB/ResultSet/Problem.pm:162]: I don't see a reason why this search shouldn't include $attrs in the same way as the search below does.

Sorry if I'm missing something...

**Comment by joesiltberg** [comment]
Woohoo #3000 ! 🥳🍾🎉

:-)
