### PR TITLE
Issues/2005 ie chart fixes

### LINKED ISSUE #2005: [fixmystreet.com] Check chart.js dashboard charts in IE8–11
I don’t think chart.js works at all in IE8, so we should check that the `/reports` and `/reports/<area>/summary` pages work fine without it.

There also look to be some chart.js rendering issues in IE9, and in IE10–11 the big "pull out" numbers on the chart at the top of `/reports` are way too far right, suggesting either a CSS issue, or a chart.js issue.

### PR DESCRIPTION
**Pull request by wrightmartin**
Fixes #2005 

All charts render in IE10+ and look fine, IE9 and below get the same content just not presented in quite the same way, but it doesn't look broken

### CODE REVIEW

File: web/js/dashboard.js [hunk 1]
```diff
@@ -1,276 +1,276 @@
 $(function(){
+    if (!$('html').is('.ie9')) {
```
Comment (zarino) [inline web/js/dashboard.js]: Rather than indenting the entire contents of this `$(function(){` block, how about just bailing out early? Like…

```javascript
$(function(){
    if ( $('html').is('.ie9') ) {
        return;
    }

    Chart.defaults.global.defaultFontSize = 16;
    …
```

File: web/cobrands/sass/_dashboard.scss [hunk 2]
```diff
@@ -60,7 +60,6 @@
 
     canvas {
         width: 100% !important;
-        height: auto !important;
```
Comment (zarino) [inline web/cobrands/sass/_dashboard.scss]: I think you missed the word "height" out of your commit message for this one!

File: web/cobrands/sass/_dashboard.scss [hunk 3]
```diff
@@ -95,6 +95,8 @@
         position: absolute;
         margin-top: -1em;
         margin-#{$right}: 0;
+        right: 0;
+        width: 18%;
```
Comment (zarino) [inline web/cobrands/sass/_dashboard.scss]: Could we maybe get a comment here to explain the `18%` magic number? I assume it’s the `padding-right: 20%` from `.labelled-line-chart` minus an extra `2%` gutter?

File: web/cobrands/sass/_dashboard.scss (hunk 2 above)
Comment (wrightmartin) [reply web/cobrands/sass/_dashboard.scss]: Fixed!
